### ISSUE TITLE
Use context manager for file handling in codebase

### ISSUE THREAD

**Issue by wjbmattingly** [project-lux/data-pipeline#177]
## Current Behavior
Many Python files currently uses direct `open()` which requires manually closing each file.

## Proposed Change
Replace direct `open()` calls with Python's context manager (`with` statement) to ensure proper file handling and automatic cleanup.

## Rationale
1. Performance remains the same
2. `with` ensures proper file handling and automatically closes the file when done, even if an exception occurs
3. Prevents potential resource leaks from unclosed file handles

## Code Changes
```python
# Before
fh = open('nohup.out')
while not finished:
    lines = fh.readlines()
    # ... rest of the while loop ...

# After
with open('nohup.out') as fh:
    while not finished:
        lines = fh.readlines()
        # ... rest of the while loop ...
```

## Implementation Notes
- This is a best practice change that implements the context manager protocol
- No functional changes to the core logic
- Improves resource management and exception handling

## Files Affected

- [x] 1. ./pipeline/storage/cache/filesystem.py
- [x] 2. ./pipeline/storage/marklogic/ml_lexer.py
- [x] 3. ./pipeline/storage/idmap/filesystem.py
- [x] 4. ./pipeline/storage/idmap/redis.py
- [x] 5. ./pipeline/sources/internal/library/mapper.py
- [x] 6. ./pipeline/sources/internal/library/loader.py
- [x] 7. ./pipeline/sources/internal/ipch/loader.py
- [x] 8. ./pipeline/sources/internal/final/mapper.py
- [x] 9. ./pipeline/sources/external/ror/loader.py
- [x] 10. ./pipeline/sources/external/geonames/loader.py
- [x] 11. ./pipeline/sources/external/viaf/loader.py
- [x] 12. ./pipeline/sources/external/viaf/index_loader.py
- [x] 13. ./pipeline/sources/external/lc/mapper.py
- [x] 14. ./pipeline/sources/external/lc/loader.py
- [x] 15. ./pipeline/sources/external/dnb/mapper.py
- [x] 16. ./pipeline/sources/external/dnb/loader.py
- [x] 17. ./pipeline/sources/external/wikidata/loader.py
- [x] 18. ./pipeline/sources/external/wikidata/index_loader.py
- [x] 19. ./pipeline/sources/external/getty/harvester.py
- [x] 20. ./pipeline/sources/external/getty/fetcher.py
- [x] 21. ./pipeline/process/validator.py
- [x] 22. ./pipeline/process/update_manager.py
- [x] 23. ./pipeline/process/reference_manager.py
- [x] 24. ./pipeline/process/base/mapper.py
- [x] 25. ./experiments/test-gemini-results.py
- [x] 26. ./experiments/gemini-places.py
- [x] 27. ./scripts/storage/make_test_dataset.py
- [x] 28. ./scripts/storage/populate-timestamps.py
- [x] 29. ./scripts/storage/watch-mlcp.py
- [x] 30. ./scripts/storage/manage-data.py
- [x] 31. ./scripts/storage/google-sames-diffs.py
- [x] 32. ./scripts/storage/make-wd-differents.py
- [x] 33. ./scripts/storage/merge-metatypes.py
- [x] 34. ./scripts/runs/run-reconcile.py
- [x] 35. ./scripts/runs/run-merge.py
- [x] 36. ./scripts/runs/run-export.py

## Tasks
- [x] Identify files that need updating
- [x] Update each file in a separate branch
- [ ] Use this opportunity to remove unnecessary files
- [x] Test the pipeline to make sure the pipeline continues to run as expected

**Comment by kkdavis14** [comment]
Specific example for why this change is necessary: the geonames loader was missing an `fh.close()` statement in `load()`.

**Comment by wjbmattingly** [comment]
Good to know there's a specific example! Maybe we should bump up the priority of this?

**Comment by kkdavis14** [comment]
file is opened here:

https://github.com/project-lux/data-pipeline/blob/bceb1868af8f56ded8a54853ad99aa354e4826d6/pipeline/sources/general/geonames/loader.py#L48

but not closed.

**Comment by azaroth42** [comment]
:blush: Good catch!
