### ISSUE TITLE
Add Configuration Files for Internal and External Data Sources

### ISSUE THREAD

**Issue by wjbmattingly** [project-lux/data-pipeline#180]
## Background
We may want to organize our data source configurations into a dedicated config folder, with separate files for each internal and external source. This will improve maintainability and make it easier to manage different data sources for new users. These configs should remove the sensitive internal data, such as API keys and local folders used on the Lux server.

## Description
Create a new `config` folder that will contain JSON configuration files for each data source. Each config file will specify the source's properties including namespace, matching patterns, fetch URLs, activity streams, and associated classes for mapping, loading, and harvesting.

### Changes Required
1. Create a new `config` directory in the project root
2. Move existing source configurations into individual JSON files
3. Update the structure to use arrays for dump files
4. Remove totalRecords field as it's no longer needed

## Example Configuration Format
```json
{
  "name": "ycba",
  "type": "internal",
  "namespace": "https://ycba-lux.s3.amazonaws.com/v3/",
  "matches": ["ycba-lux.s3.amazonaws.com/v3/"],
  "fetch": "https://ycba-lux.s3.amazonaws.com/v3/{identifier}",
  "activitystreams": [
    "https://ycba-lux.s3.amazonaws.com/activity_stream/collection1.json"
  ],
  "merge_order": 1,
  "mapperClass": "sources.yale.ycba.mapper.YcbaMapper",
  "loaderClass": "sources.yale.ycba.loader.YcbaLoader",
  "harvesterClass": "process.base.harvester.ASHarvester",
  "dumpFiles": [
    "ycba/linked_art.tar.gz"
  ]
}
```

## Tasks
- [x] Create new `config` directory in project root
- [ ] Create subdirectories for internal and external sources
- [x] Create JSON schema to validate configuration files
- [x] Create example configuration file following new format
- [ ] Update documentation to reflect new configuration structure #179 
- [x] Write tests to validate configuration loading
- [ ] Update existing code to use new configuration files
- [ ] Update the mapper, loader, and harvesters to align with the new source folder structure #174 
- [ ] Remove the sample_configs folder in docs/

## Related Issues
- #179 Provide Scripts for Downloading Data
- #174 Re-organize sources for clarity

**Comment by kkdavis14** [comment]
@wjbmattingly all external config files have been created and pushed to v0.0.2. 
as a result of updating these, several new tasks emerged:
#198 
#195 
#188 
#187

**Comment by wjbmattingly** [comment]
@kkdavis14 Thanks for the update!!
