### ISSUE TITLE
Scheduler for Downloaders

### ISSUE THREAD

**Issue by wjbmattingly** [project-lux/data-pipeline#183]
## Description

While developing our downloaders, we noted that it would be useful to be able to automate them in some fashion via specified time intervals. While this works for some external sources that update regularly, not all external sources provide such consistency. Some, such as VIAF, update irregularly and need to be flagged for update.

## Task
- [x] Identify how external data dumps are updated and at what intervals
- [ ] ~~Develop config schemas that capture this variance~~
- [x] Write a scheduler.py file in scripts/download/ that uses the configs to then call scripts/download/downloader.py for the specific source.

**Comment by kkdavis14** [comment]
I think we can decide what download schedule we want, as the externals are all over the place. Some are nightly, some are yearly, and often times they don't specify at all. 

To close this:

- [ ] Update scheduler.py file for ROR and ORCID
- [ ] confirm the scheduler.py file is working as intended with all necessary functionality
- [ ] Schedule cron job to run scheduler on agreed upon cadence

**Comment by kkdavis14** [comment]
closing in favor of new repo.
